# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(" background:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_list = QtWidgets.QListWidget(self.centralwidget)
        self.image_list.setGeometry(QtCore.QRect(10, 60, 191, 501))
        self.image_list.setStyleSheet("border:2px solid rgb(85, 255, 0);\n"
"border-radius: 10px;\n"
"background:orange;")
        self.image_list.setObjectName("image_list")
        self.papka_btn = QtWidgets.QPushButton(self.centralwidget)
        self.papka_btn.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.papka_btn.setStyleSheet("border:2px solid rgb(85, 255, 0);\n"
"border-radius: 10px;\n"
"background:orange;")
        self.papka_btn.setObjectName("papka_btn")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(210, 260, 49, 13))
        self.image_label.setObjectName("image_label")
        self.left_btn = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn.setGeometry(QtCore.QRect(210, 520, 91, 31))
        self.left_btn.setStyleSheet("border:2px solid rgb(85, 255, 0);\n"
"border-radius: 10px;\n"
"background:orange;")
        self.left_btn.setObjectName("left_btn")
        self.right_btn = QtWidgets.QPushButton(self.centralwidget)
        self.right_btn.setGeometry(QtCore.QRect(310, 520, 91, 31))
        self.right_btn.setStyleSheet("border:2px solid rgb(85, 255, 0);\n"
"border-radius: 10px;\n"
"background:orange;")
        self.right_btn.setObjectName("right_btn")
        self.mirror_btn = QtWidgets.QPushButton(self.centralwidget)
        self.mirror_btn.setGeometry(QtCore.QRect(420, 520, 91, 31))
        self.mirror_btn.setStyleSheet("border:2px solid rgb(85, 255, 0);\n"
"border-radius: 10px;\n"
"background:orange;")
        self.mirror_btn.setObjectName("mirror_btn")
        self.sharp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sharp_btn.setGeometry(QtCore.QRect(530, 520, 91, 31))
        self.sharp_btn.setStyleSheet("border:2px solid rgb(85, 255, 0);\n"
"border-radius: 10px;\n"
"background:orange;")
        self.sharp_btn.setObjectName("sharp_btn")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 520, 91, 31))
        self.pushButton.setStyleSheet("border:2px solid rgb(85, 255, 0);\n"
"border-radius: 10px;\n"
"background:orange;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.papka_btn.setText(_translate("MainWindow", "папка"))
        self.image_label.setText(_translate("MainWindow", "Картинка"))
        self.left_btn.setText(_translate("MainWindow", "Ліворуч"))
        self.right_btn.setText(_translate("MainWindow", "Праворуч"))
        self.mirror_btn.setText(_translate("MainWindow", "Дзеркало"))
        self.sharp_btn.setText(_translate("MainWindow", "Різкість"))
        self.pushButton.setText(_translate("MainWindow", "Ч/Б"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
